# fly.toml app configuration file generated for hoof-worker on 2024-12-07T19:58:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hoof-worker'
primary_region = 'ewr'

[build]

[env]
  WORKER_EXIT_WHEN_DONE = 'true'
  S3_ENDPOINT = "https://fly.storage.tigris.dev"
  S3_BUCKET = "hoof-storage"
  POSTGRES_URL = "postgresql://hoof-db.internal/postgres"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
