# fly.toml app configuration file generated for hoof-api on 2024-12-07T18:47:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hoof-api'
primary_region = 'ewr'

[build]

[deploy]
  strategy = "bluegreen"
  release_command = "java -cp /app/server.jar com.playfulprogramming.cms.FlywayMigrateKt"

[env]
  CLIENT_URL = "https://playfulprogramming.com"
  S3_PUBLIC_URL = "https://fly.storage.tigris.dev"
  S3_BUCKET = "hoof-storage"
  POSTGRES_URL = "postgresql://hoof-db.internal/unicorn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
