name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # ensure only one deploy action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Deploy Worker
        run: flyctl deploy --remote-only
        working-directory: ./worker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WORKER_DEPLOY_TOKEN }}
      - name: Deploy API
        run: flyctl deploy --remote-only
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_DEPLOY_TOKEN }}
